### ISSUE TITLE
Feature Request - Layout in Landscape mode

### ISSUE THREAD

**Issue by Tommy-LSA** [acomminos/Plumble-Legacy#11]
It would be fine if the Layout would switch to the Layout used on Tablets if mobile flip to the landscape mode. Means that Userlist is visible as well as the chat frame.

**Comment by acomminos** [comment]
Sounds like a great idea. How does 640dip minimum horizontal width sound for invoking that layout (so, Galaxy Nexus and above class devices)?

**Comment by Tommy-LSA** [comment]
Well, good point. Best way would be then to detect the resolution. 
On SGS I have performed some tests by simply add a folder /layout-land an copy the 600dp Tablet XML into it. Looks good so far with 50/50 delimiter. Only text of PTT key is a bit long and touches the tickbox (at least the German text). A linebreak could help there
Issue what I see on this test was a nullpointer exception while flip back to portrait:
at com.morlunk.mumbleclient.app.ChannelListFragment.updateChannel(ChannelListFragment.java:98)

I haven't invested time to find the issue but I think there is some crap in the saved instance while rotating and the views dosn't match after rotate

**Comment by acomminos** [comment]
Implemented in latest commit. That was way too tricky to fix D:
