### ISSUE TITLE
Plumble randomly exits when running in the background.

### ISSUE THREAD

**Issue by Tritonio** [acomminos/Plumble-Legacy#110]
I have this problem on two different mobiles and it's been around for months.

Procedure:
I connect to server. I can talk to people. I leave by pressing the home button. Plumble oviously runs in the background and the hot corner works. I open another app (or just stay on my home screen). At some random point Plumble will simply vanish from the notification area ad the whole program is now not running.

Here is my device info and a logcat:
build.board: DB8520H
build.bootloader: unknown
build.brand: samsung
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: golden
build.display: JZO54K.I8190XXAMB3
build.fingerprint: samsung/goldenxx/golden:4.1.2/JZO54K/I8190XXAMB3:user/release-keys
build.hardware: samsunggolden
build.host: SEP-82
build.id : JZO54K
build.manufacturer: samsung
build.model: GT-I8190
build.product: goldenxx
build.radio: unknown
build.serial: 4790f043dbbabf52
build.tags: release-keys
build.time: 1360913911000
build.type: user
build.user: se.infra
version.codename: REL
version.incremental: I8190XXAMB3
version.release: 4.1.2
version.sdk_int: 16

04-12 23:45:57.405 I/Plumble (5780): MumbleService: Created
04-12 23:45:57.435 I/Plumble (5780): MumbleService: Bound
04-12 23:45:57.805 I/Plumble (5780): com.morlunk.mumbleclient.app.ConnectedActivityLogic: Disconnected
04-12 23:45:59.637 I/Plumble (5780): MumbleService: Starting service
04-12 23:45:59.647 I/Plumble (5780): Connecting to host "bittit.info ", port 64738
04-12 23:45:59.727 I/Plumble (5780): com.morlunk.mumbleclient.app.ConnectedActivityLogic: Connecting
04-12 23:45:59.797 I/Plumble (5780): MumbleService: Connection state changed to Connecting
04-12 23:46:00.070 I/Plumble (5780): com.morlunk.mumbleclient.app.ConnectedActivityLogic: Connecting
04-12 23:46:00.330 I/Plumble (5780): Loaded 1 client certificate(s).
04-12 23:46:00.910 I/Plumble (5780): TTS enabled.
04-12 23:46:01.470 I/Plumble (5780): UDP Socket opened
04-12 23:46:01.500 D/Plumble (5780): <<< Version
04-12 23:46:01.500 D/Plumble (5780): <<< Authenticate
04-12 23:46:01.500 W/Plumble (5780): unhandled message type Version
04-12 23:46:01.510 I/Plumble (5780): com.morlunk.mumbleclient.app.ConnectedActivityLogic: Synchronizing
04-12 23:46:01.510 I/Plumble (5780): MumbleService: Connection state changed to Synchronizing
04-12 23:46:03.432 D/Plumble (5780): MumbleConnection: CryptSetup
04-12 23:46:03.502 W/Plumble (5780): unhandled message type PermissionQuery
04-12 23:46:03.502 W/Plumble (5780): unhandled message type PermissionQuery
04-12 23:46:03.572 D/Plumble (5780): >>> ServerSync
04-12 23:46:03.572 D/Plumble (5780): <<< UserState
04-12 23:46:03.572 W/Plumble (5780): unhandled message type SuggestConfig
04-12 23:46:03.572 I/Plumble (5780): Selected recording sample rate: 48000
04-12 23:46:03.602 I/Plumble (5780): AudioUser created
04-12 23:46:03.642 I/Plumble (5780): com.morlunk.mumbleclient.app.ConnectedActivityLogic: Connected
04-12 23:46:03.662 I/Plumble (5780): MumbleService: Connection state changed to Connected
04-12 23:46:03.702 D/Plumble (5780): <<< Authenticate
04-12 23:46:03.722 I/Plumble (5780): AudioOutput: Enough data buffered. Starting audio.
04-12 23:46:27.976 I/Plumble (5780): AudioUser created
04-12 23:46:49.727 I/Plumble (5780): AudioOutput: Standby timeout reached. Audio paused.
04-12 23:46:54.032 I/Plumble (5780): AudioOutput: Enough data buffered. Starting audio.
04-12 23:47:58.356 I/Plumble (5780): AudioOutput: Standby timeout reached. Audio paused.
04-12 23:48:19.308 I/Plumble (5780): AudioOutput: Enough data buffered. Starting audio.
04-12 23:48:40.188 I/Plumble (5780): AudioOutput: Standby timeout reached. Audio paused.
04-12 23:48:40.949 I/Plumble (5780): AudioOutput: Enough data buffered. Starting audio.
04-12 23:48:47.555 W/Plumble (5780): unhandled message type PermissionQuery
04-12 23:48:49.227 I/Plumble (5780): AudioOutput: Standby timeout reached. Audio paused.
04-12 23:50:54.542 I/Plumble (6634): MumbleService: Created

Please note how the last logcat message has a different PID (6634) even though I did NOT restart Plumble. I simply watched it die and then opened my logcat viewer to export this log.

**Comment by Zuko** [comment]
out of ram?

2013/4/12 Tritonio notifications@github.com

**Comment by Tritonio** [comment]
I don't think it was that bad but it could be that. In either case, when I run Plumble as a background service then I expect it to keep running. By the same reasoning my system should also kill my music player or my torrent client or Viber but it doesn't.

AFAIK you can designate a service as foreground to avoid Android killing it.

**Comment by acomminos** [comment]
Fixed the memory issue by running in foreground. My mistake, I had forgot to throw that back in when adding chat notifications.
