### ISSUE TITLE
Enhancement - P2P chat icon in dark theme

### ISSUE THREAD

**Issue by Tommy-LSA** [acomminos/Plumble-Legacy#12]
The P2P chat icon is nearly invisible on dark theme. please use two icons or an icon which is colored to be visible in dark theme as well as in white theme

I cannot see a different - try it in Emulator with dark theme

**Comment by acomminos** [comment]
I really need to fix the naming of the resources- they're pretty haphazardly labelled. I'll go and see if I can start adding dark layout resources in the process.

**Comment by Tommy-LSA** [comment]
You do a great job and u'll definitly find a way :-) Actually Plumble is miles better then the IOS Mumble.

**Comment by acomminos** [comment]
Fixed in upstream. Thanks again for the report, I rarely use dark theme.

**Comment by Tommy-LSA** [comment]
I cannot see a different - try it in Emulator with dark theme

**Comment by acomminos** [comment]
Weird. Here's how it looks for me as of commit 9b5a52f3365cc79498d3511386f9f3d3c8c3bdb6:

http://i.imgur.com/xohpd.png

Let me try in emulator.

**Comment by Tommy-LSA** [comment]
Sorry, my fault. Eclipse hasn't synced the source. Unfortunately after syncing I get a crash while opening the preferences

12-28 07:57:07.533: E/AndroidRuntime(738): Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
12-28 07:57:07.533: E/AndroidRuntime(738):  at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:242)
12-28 07:57:07.533: E/AndroidRuntime(738):  at android.preference.Preference.getPersistedBoolean(Preference.java:1630)
12-28 07:57:07.533: E/AndroidRuntime(738):  at android.preference.TwoStatePreference.onSetInitialValue(TwoStatePreference.java:184)
12-28 07:57:07.533: E/AndroidRuntime(738):  at android.preference.Preference.dispatchSetInitialValue(Preference.java:1315)

**Comment by Tommy-LSA** [comment]
Everything is OK! I got the official update over Playstore and everything is fine. My Dev environment seems to be suboptimal :-/
