### ISSUE TITLE
Automatic reconnect and channel rejoin

### ISSUE THREAD

**Issue by alcatraz-zz** [acomminos/Plumble-Legacy#120]
Hi Morlunk

Has this been implemented yet?

/Mike

**Comment by acomminos** [comment]
Hi Mike,

Yes, this has been implemented! In order to rejoin the channel automatically however, you need to be registered on the server with a certificate.

Thanks,
Andrew

**Comment by alcatraz-zz** [comment]
Hey Andrew

We can't seem to register using Plumble. The server is 1.2.3 and the computer client can register normally. The error message trying to register is "permission denied". Any idea?

Or is register and "certificate" two different things here?

/Mike

**Comment by acomminos** [comment]
Hi,

You need to make a certificate in settings before trying to register.

**Comment by alcatraz-zz** [comment]
Hey Andrew

The registration is complete but the autoconnect doesnt seem to work. We just tried to go offline and online on the wifi connection but never rejoined. (There was no other connection available to fall back to during the offline period)

Is the automatic update on android play working like it should? I'm suspecting maybe it's not updating automatically since the version number doesnt seem to change with your updates Could it be that the program needs to be manually updated by uninstalling and reinstalling?

It could be the reason we are not getting all the features.

/Mike

**Comment by acomminos** [comment]
Hi Mike,

Right now all the changes I've made are in the Plumble source code, available here on GitHub. I'll be pushing the new version tonight or tomorrow.

Thanks,
Andrew

**Comment by acomminos** [comment]
It's live on Play now.
