### ISSUE TITLE
Jitter buffer

### ISSUE THREAD

**Issue by alcatraz-zz** [acomminos/Plumble-Legacy#123]
Hey Andrew!

I saw that the old Mumble app used a jitter buffer which Plumble doesn't seem to have. 

I've gotten Plumble almost perfect except for when the phone is in screen lock mode the incoming transmissions sound jittery and roboty. Would a jitter buffer solve that? (The outgoing transmissions sound good under screen lock - voice activation)

How come it's all jittery only during screen lock?

I tried bumping up the screen lock cpu performance without any success. (rooted + system tuner)

Can it have something to do with me using an old android version 2.2. froyo? I could hack update it to 4.0.4 ICS but I don't think it would solve the problem. Any ideas anyone?

/Mike

**Comment by acomminos** [comment]
Hi Mike; while implementing the Speex jitter buffer support is in the works, I don't think its absence is causing your problems, as its function is to improve the management of packet order. There is indeed a wakelock that is set when the screen is turned off that would seemingly resolve that issue. When I can, I'll check out that code and make sure it's working on 2.2 devices.

**Comment by alcatraz-zz** [comment]
Thanks for the reply Andrew

The issue was just like you said not Mumble/Plumble related at all. It was cpu-related. I simply installed a cpu manage app and changed the screen lock profile to allow for higher ondemand cpu performance.

Cheers!
/Mike
