### ISSUE TITLE
Wrong certificate or password for existing user

### ISSUE THREAD

**Issue by tristanlins** [acomminos/Plumble-Legacy#126]
I imported my p12 certificate from PC on my phone, but when I try to connect I always get an error

> <W>2013-09-26 17:12:02.570 1 => 27:tril(-1) Rejected connection from ....:23177: Wrong certificate or password for existing user

Plumble version 2.0.0a
Server version 1.2.4

**Comment by Zuko** [comment]
You must use "strong" certificate like this one:
http://mumble.sourceforge.net/Obtaining_a_Comodo_Certificate

2013/9/26 Tristan Lins notifications@github.com

**Comment by tristanlins** [comment]
Okay, thx I will try this out :-)
