### ISSUE TITLE
After git clone import import com.morlunk.mumbleclient.R; not found

### ISSUE THREAD

**Issue by PeterMeyer** [acomminos/Plumble-Legacy#13]
1) I cloned the archive 
2)) done the android update project -p Plumble and local.properties was added

But there are a Class not found Error regarding import com.morlunk.mumbleclient.R;
The Sourcefile for import com.morlunk.mumbleclient.R.java is not in the checkout and 
not in the sourcetree but hundreds of time referenced in the entire project.

**Comment by acomminos** [comment]
Hi, did you follow the tutorial for building here?

https://github.com/Morlunk/Plumble/wiki/Building-Plumble

Thanks,
Andrew

**Comment by PeterMeyer** [comment]
Yeah witj the Exception thadt i use Windows Vista 64 and the Standard Eclipse Bundle + Integrated Android Toolkit Chain. Is there any special Eclipse Version (Juno 4.x or above) i should use? I also noticed thadt the Google Standard Android Bundle doenst has NDK support. I simply just trying to git clone and doing a andoird update project -p myplumble_checlout update to get an valid local.properties file wich points to the correct sdk.dir (in my case  F:\adt-bundle-windows-x86_64\sdk (inside the Google Eclipse Bundle from http://developer.android.com/sdk/index.html).

ps:
Can you please a bit more specific what

Fetch the submodules
Before even touching the project, let's get its dependencies.

git submodule init
git submodule update

Excactly means? What submodule?? its not very clear i think.

Peter

**Comment by acomminos** [comment]
The project depends on a few submodules; namely speex, ActionBarSherlock, CELT, and opus. To fetch these, you type in those commands in a git shell in the project directory.

**Comment by PeterMeyer** [comment]
In the Wiki Section you descibed under "Updating native library (optional)" thadt no JNI Subproject
build is needed for a simple checkout and building plumle but obviously now you need to fetch and build
the JNI Subprojects in anycase after a fresh checkout? Confusing... Wich NDK Version is needed and is there any
specific NDK Envvar i have to register for the JNI Subprojects like $(NDK_HOMME) or something like this?

The other Problem.You described in the Wiki its done with updating the Android Tool Lib with Rightclick in the Projecttree in Eclipse. I have done it and Eclipse download a Jar File, integrated it to the Project but it doesnt 
solve any broken imports related to the Actionbar Component, even after doing a clean and build rerun or
using ANT Target 1 or 2 it allways comes up with a hugh Text and says anything works fine (succesfull build)
but nothing happend, no Debug/Release and no Run Configuration to the Sim is shown. 

How you build/deploy and run the builded Plumble App up against the Android Device Sim? 
Which Device Profile is ok and is Plumble only running on Jelly Beans 4.2 only?

**Comment by acomminos** [comment]
Sorry for the confusion; you DO need to fetch ActionBarSherlock, which is a submodule, and then add the updated support library to it after adding it to eclipse. Plumble will run on Android version 2.1 and above, however is recommended on devices 4.0+.

**Comment by PeterMeyer** [comment]
Ok, i will check this out.
Can you please describe how i can start the Pluble App if builded? It looks like there is no Ant Target for deploy or something or Debug. If i create a new Android App from scratch i can rightclick and run as Android App or Debug the App, but in the case of Plumble i see nothing like this. How can i run pluble after successfull build in the Android Simulator? Thx

**Comment by acomminos** [comment]
Closing, I'll make another issue for x86 native libraries.
