### ISSUE TITLE
[BUG] - "Synchronizing data with Mumble" takes "forever" on bigger servers.

### ISSUE THREAD

**Issue by Zuko** [acomminos/Plumble-Legacy#26]
Tested on latest code from git. 
Connection to local empty server (0 channels, 0 users) is immediate, but on large server it takes too much time (~3min).

Tested servers: 
hlds.pl:64739 and m1.svoice.pl:60000

**Comment by acomminos** [comment]
Confirmed, thanks for the report. Is this a regression?

**Comment by Zuko** [comment]
yes
02-01-2013 22:59, "Andrew Comminos" notifications@github.com napisał(a):

**Comment by acomminos** [comment]
Fixed in `f126aac`. Closing.
