### ISSUE TITLE
[BUG] - Some transalted strings are still in english

### ISSUE THREAD

**Issue by Zuko** [acomminos/Plumble-Legacy#27]
1. http://syf.z.hlds.pl/2013-01-02_13-21-39.png
2. http://syf.z.hlds.pl/2013-01-02_13-22-19.png
3. http://syf.z.hlds.pl/2013-01-02_13-26-08.png - theme name in xml is different than in app oO

**Comment by acomminos** [comment]
Not getting this problem here.

http://i.imgur.com/e3mJS.png

Have you tried cleaning the project in Eclipse (Project->Clean) and then rebuilding? That's more than likely the issue.

**Comment by Zuko** [comment]
yes, I must always do "clean" after merging your code into my fork
weird

**Comment by acomminos** [comment]
This should be fixed by going into the Project menu and selecting Build Automatically. You may have to disable that option when you export the project into an APK, due to a bug in the current version of ADT.

Is this safe to close for now?

**Comment by Zuko** [comment]
yes, I will try to fix it myself because it's a bug in my eclipse

**Comment by Zuko** [comment]
Fixed, I just re-import my fork to eclipse
