### ISSUE TITLE
[BUG] - Favorite channel icon

### ISSUE THREAD

**Issue by Zuko** [acomminos/Plumble-Legacy#29]
Icon is displayed incorrectly after rotating the screen.
Steps:
1. mark channel as favorite (in menu) - http://syf.z.hlds.pl/2013-01-02_13-45-23.png
2. rotate the screen
3. channel is not marked as favorite - http://syf.z.hlds.pl/2013-01-02_13-46-35.png

**Comment by Zuko** [comment]
Only in Android <4.0.4

**Comment by acomminos** [comment]
More than likely an issue with ActionBarSherlock's implementation. I'll look into this and see if I can fix it.

**Comment by acomminos** [comment]
Fixed in upstream. Thanks for the report.
