### ISSUE TITLE
Expandable channel list

### ISSUE THREAD

**Issue by nvtkaszpir** [acomminos/Plumble-Legacy#38]
In mumble client there is an option to expand/hide the subchannels.
The Plumble does not have that feature, which is quite annoying on very complicated servers.

Would be nice to completely change the method of browsing the subchannels.
For example there is known method of browsing directories, where root dirs are on left, pressing on the item causes it to expand to the right, showing it children (this is very known in iphone/ipod music browsing).

Of course there can be issue with patents...

Another idea would be to allow expandable elements in the menu, but not sure if this is possible (actually I don't remember if  I saw tis in any android app).

Another option would be to limit the nesting for the current view to for example maximum 2 levels deep.

**Comment by Zuko** [comment]
+1

**Comment by acomminos** [comment]
Done. See upstream!
