### ISSUE TITLE
[BUG] You can't hear anybody when "force TCP" connection is off (on udp)

### ISSUE THREAD

**Issue by Zuko** [acomminos/Plumble-Legacy#48]
Latest version from Google Play, android 4.0.4 (server v1.2.4)

**Comment by strandedPL** [comment]
confirmed, ICS 4.0.4

**Comment by acomminos** [comment]
This should have been fixed in one of my commits last week involving problems with UDP connectivity. I'll review the issue.

**Comment by acomminos** [comment]
Oh, didn't see that you were using the Google Play version. This fix + much better opus support will be in the next release.

Closing, please comment if you're still getting this bug from upstream.
