### ISSUE TITLE
Untranslatable strings

### ISSUE THREAD

**Issue by Zuko** [acomminos/Plumble-Legacy#53]
When "chat" strings will be translatable? (I found you comment in code)

**Comment by acomminos** [comment]
Just added to the latest commit- going to close. Feel free to re-open if you find any more strings that need to be isolated.

Thanks!

**Comment by Zuko** [comment]
Ok, I need more strings.
1. I need "%s is now unmuted and undeafened". - I can't use same string for unmuted for "unmuted and undeafeaned" event in polish
2. Where is disconnected message?

btw. I can't reopen this ticket.
