### ISSUE TITLE
NDK error when following build instructions

### ISSUE THREAD

**Issue by ankushg** [acomminos/Plumble-Legacy#55]
When following the steps outlined on the wiki page, Eclipse gives me this error `Android NDK: WARNING: APP_PLATFORM android-14 is larger than android:minSdkVersion 7 in ./AndroidManifest.xml` in this file `line 128, external location: /Users/dev/Development/adt-bundle-mac-x86_64/android-ndk-r8d/build/core/add-application.mk`

**Comment by acomminos** [comment]
This is a known bug with the latest NDK.

http://code.google.com/p/android/issues/detail?id=39752

See the thread for a solution.

**Comment by ankushg** [comment]
Awesome, thanks! For anyone who gets this same error and wants to fix it, https://code.google.com/p/android/issues/detail?id=39752#c7 in particular is the post that explains what to do.

Closed.
