### ISSUE TITLE
[FEATURE] Bluetooth-Headset support

### ISSUE THREAD

**Issue by scomans** [acomminos/Plumble-Legacy#59]
Could you add support for bluetooth headsets.
This would be a great improvement to Plumble.

**Comment by acomminos** [comment]
Sure. I'll see if I can get my hands on a bluetooth audio device to work with.

**Comment by Zuko** [comment]
http://developer.android.com/guide/topics/connectivity/bluetooth.html

**Comment by Gerdal** [comment]
Actually I see only one main problem in working with bluetooth headet. I can hear people but I can't talk with them because sound is recorded by microphone built in phone. I can't talk with them when I have phone in pocket...

**Comment by acomminos** [comment]
Added :) the reason you didn't hear people before was because A2DP (high quality bluetooth audio) is automatically turned on by Android, but is only one-way.
