### ISSUE TITLE
[BUG] Problem after kick (maybe after ban too)

### ISSUE THREAD

**Issue by Zuko** [acomminos/Plumble-Legacy#76]
Do these few steps and you will see whats wrong.
1. Open Plumble ;)
2. Connect to any server
3. Kick yourself (from another client)
4. Lock your screen
5. Unlock your screen
6. Look at your notification bar and try to "open" Plumble from there
7. and 5. can be replaced by "home" button - but then you must "open" Plumble from "App list" and press "back"

**Comment by acomminos** [comment]
Fixed in fcb5d6d497cefa0c5756fae8c93ec983dbe94d0c. Thanks for the report!
