### ISSUE TITLE
NDK-build always failed

### ISSUE THREAD

**Issue by ram4soft** [acomminos/Plumble-Legacy#79]
Hi guys,
I downloaded the plumble client for android source code and followed the installation instructions but when i tried to run it, i always get in the console
{
***\* Build of configuration Default for project PlumbleClient ****

sh ndk-build all 
ERROR: You are using a non-Cygwin compatible Make program.
Currently using: D:/Java/cygwin/bin/make

To solve the issue, follow these steps:
1. Ensure that the Cygwin 'make' package is installed.
   NOTE: You will need GNU Make 3.81 or later!
2. Define the GNUMAKE environment variable to point to it, as in:
   
    export GNUMAKE=/usr/bin/make
3. Call 'ndk-build' again.

***\* Build Finished ****
}

i'm using GNU Make 3.82.90 and  ndk-r8 
when i tried to build the jni files with this command
D:\Java\PlumbleClient\jni>ndk-build
I got this error also
{
....
....
In file included from D:/Java/PlumbleClient//jni/new/hawtjni_native.c:2:0:
D:/Java/PlumbleClient//jni/new/hawtjni_native.h:4:18: fatal error: celt.h: No su
ch file or directory
compilation terminated.
make: **\* [D:/Java/PlumbleClient//obj/local/x86/objs/NativeAudio/hawtjni_native.
o] Error 1
}
please try to help
Thanks
Ram

**Comment by acomminos** [comment]
Hi,

Currently, I only test building on OS X and Linux (Arch Linux and Ubuntu, in particular). Unfortunately I can't recommend a solution for your problem as I don't have a Windows machine to work with at the moment :( Please try asking a Windows Android dev.

Thanks,
Andrew

**Comment by acomminos** [comment]
For now I'm going to close this as it's not an issue with Plumble as a project.
