### ISSUE TITLE
Building Plumble for 2.3.3

### ISSUE THREAD

**Issue by ram4soft** [acomminos/Plumble-Legacy#82]
Hi, Is there a compatible code version for 2.3 devices or even a guide for achieving this with the current 4.2 versions ?
Thanks
Ram

**Comment by Zuko** [comment]
Plumble works on 2.3.x, but has some UI problems

2013/3/11 ram4soft notifications@github.com

**Comment by ram4soft** [comment]
Thanks Zuko for reply

**Comment by acomminos** [comment]
Thanks for replying, Michal. Closing this issue, please refer to https://github.com/Morlunk/Plumble/issues/28 for further updates.
