### ISSUE TITLE
Translation tool 

### ISSUE THREAD

**Issue by Zuko** [acomminos/Plumble-Legacy#84]
http://code.google.com/p/android-php-translator/

**Comment by Zuko** [comment]
or http://translate.google.com/toolkit

**Comment by acomminos** [comment]
Looks great. I'd like to set this up in the future, thanks for the tip.

**Comment by Zuko** [comment]
http://www.getlocalization.com/

time to choose one ;)

**Comment by Zuko** [comment]
http://reddit.com/r/AppTranslations

**Comment by acomminos** [comment]
Decided to go with GetLocalization, but they're having GitHub integration issues on their end. I'll let you know when it's up.

**Comment by acomminos** [comment]
http://www.getlocalization.com/Plumble/
