### ISSUE TITLE
Is there a java mumble client for desktop?

### ISSUE THREAD

**Issue by ram4soft** [acomminos/Plumble-Legacy#85]
Hi
Is there a java mumble client for desktop?
thanks
Ram

**Comment by Zuko** [comment]
... this is not right place for this question.

http://mumble.sourceforge.net/
https://github.com/mumble-voip/mumble

irc://irc.freenode.org/mumble

but: nope, Mumble is written in QT

2013/3/16 ram4soft notifications@github.com
