### ISSUE TITLE
Plumble crashes while downlaoding the public server list without an internet connection

### ISSUE THREAD

**Issue by jannispinter** [acomminos/Plumble-Legacy#93]
When Plumble is blocked by an android firewall (like AFWall+) or the device has no internet connection, the application crashes while downloading the public server list.

Logcat:
03-31 11:03:26.176: W/dalvikvm(3622): threadid=1: thread exiting with uncaught exception (group=0x41a8b930)
03-31 11:03:26.176: E/AndroidRuntime(3622): FATAL EXCEPTION: main
03-31 11:03:26.176: E/AndroidRuntime(3622): java.lang.NullPointerException
03-31 11:03:26.176: E/AndroidRuntime(3622):     at java.util.ArrayList.<init>(ArrayList.java:93)
03-31 11:03:26.176: E/AndroidRuntime(3622):     at com.morlunk.mumbleclient.app.PublicServerListFragment$PublicServerAdapter.<init>(PublicServerListFragment.java:198)
03-31 11:03:26.176: E/AndroidRuntime(3622):     at com.morlunk.mumbleclient.app.PublicServerListFragment.setServers(PublicServerListFragment.java:115)
03-31 11:03:26.176: E/AndroidRuntime(3622):     at com.morlunk.mumbleclient.app.ServerList$4.onPostExecute(ServerList.java:351)
03-31 11:03:26.176: E/AndroidRuntime(3622):     at com.morlunk.mumbleclient.app.ServerList$4.onPostExecute(ServerList.java:1)
03-31 11:03:26.176: E/AndroidRuntime(3622):     at android.os.AsyncTask.finish(AsyncTask.java:631)
03-31 11:03:26.176: E/AndroidRuntime(3622):     at android.os.AsyncTask.access$600(AsyncTask.java:177)
03-31 11:03:26.176: E/AndroidRuntime(3622):     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
03-31 11:03:26.176: E/AndroidRuntime(3622):     at android.os.Handler.dispatchMessage(Handler.java:99)
03-31 11:03:26.176: E/AndroidRuntime(3622):     at android.os.Looper.loop(Looper.java:137)
03-31 11:03:26.176: E/AndroidRuntime(3622):     at android.app.ActivityThread.main(ActivityThread.java:5226)
03-31 11:03:26.176: E/AndroidRuntime(3622):     at java.lang.reflect.Method.invokeNative(Native Method)
03-31 11:03:26.176: E/AndroidRuntime(3622):     at java.lang.reflect.Method.invoke(Method.java:511)
03-31 11:03:26.176: E/AndroidRuntime(3622):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
03-31 11:03:26.176: E/AndroidRuntime(3622):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
03-31 11:03:26.176: E/AndroidRuntime(3622):     at dalvik.system.NativeStart.main(Native Method)

**Comment by acomminos** [comment]
Fixed in upstream, thanks for the report. 95a73a3c43d691196b8a0df5883ab1aa32eb2863
