### ISSUE TITLE
Push-To-Talk-Button is not self-explaining anymore.

### ISSUE THREAD

**Issue by Natenom** [acomminos/Plumble-Legacy#94]
The old Push-To-Talk-Button and the previous Mic-Icon were better. With the new button you must see your user entry to know whether you are sending or not if "Toggle Push-to-Talk" is enabled.

**Comment by acomminos** [comment]
The issue with toggle not being represented properly is a bug. Will fix momentarily.

**Comment by acomminos** [comment]
Fixed toggle. I'm not sure whether the toggle option should stay in its new place (settings) or be moved back, as it was somewhat hard to press and a bit confusing to new users.

**Comment by Natenom** [comment]
I would prefer to have both. The current checkbox in settings AND and the old toggle checkbox within the push-to-talk button with the possibility to show/hide it. Default could be off for beginners.
The reason for this is, that in my case I often want to switch the push-to-talk mode depending on how I hold the device.

**Comment by acomminos** [comment]
How about a double-tap to toggle? I think that would be a reasonable solution, what about you?

**Comment by Zuko** [comment]
+1
8 kwi 2013 00:31, "Andrew Comminos" notifications@github.com napisał(a):

**Comment by acomminos** [comment]
Added double tap in upstream. Closing.
